### ISSUE TITLE
"Insert timer description" not memorizing the descriptions

### ISSUE THREAD

**Issue by sanfm12** [martakostova/pomodoro#14]
Hi,

This is my personal favorite Pomodoro app, I'm really grateful for your hard work on it.

The problem is that there is a drop down button to the right of "insert timer description" that never reveals any of my previous descriptions, in other words, it's useless.
The box will always show the last description, but the drop down button doesn't reveal the past descriptions at all.
So I have to keep typing again and again every description, which is a little troublesome.
I would really appreciate a quick fix on that.

Thank you

**Comment by sanfm12** [comment]
Hi, this issue persists on v. 2.1.0

**Comment by martakostova** [comment]
Yes, it is added in the issues list. Will be fixed soon.

**Comment by martakostova** [comment]
This was fixed in the latest version. Enjoy!
