### ISSUE TITLE
Timer stops during screen lock

### ISSUE THREAD

**Issue by afuerstenau** [martakostova/pomodoro#24]
Hi,

I am working in an open office environment and locking the screen is quite common.
The timer stops if a lock (Ctrl+Shift+Eject) my screen.

I am not absolutely sure but I think one or two os versions before Yosemite it didn't stop.

Is there some configuration change for this available? Can you reproduce it?

Thanks in advance,
Alex

**Comment by martakostova** [comment]
Hi, 
this is not changed from the very beginning. Yes I can reproduce it and it is how it is made to be. It presumes that the screen shouldn't be locked to count.
The only option related to the screen is "Prevent sleep" during timer/break.

Cheers,
Marta
