### ISSUE TITLE
Not works on OS X 10.7.5!

### ISSUE THREAD

**Issue by SashkoGarazd** [martakostova/pomodoro#27]
Hi, the app even don't run on my os x 10.7.5. I click on icon and just nothing.
![2015-02-08 23 09 24](https://cloud.githubusercontent.com/assets/10913010/6098446/b6cc6404-afe7-11e4-9929-382ca998da17.png)

**Comment by martakostova** [comment]
Hi, which version are you using? 
Future versions of the app will work for 10.8 and above, so you may need to build an older version for 10.6 or 10.7 from the source. 

Cheers,
Marta

**Comment by SashkoGarazd** [comment]
Hi, I don't know which version I have). I just bought it in the app store and there is info that it'll work on even os x 10.6! And I have os x 10.7.5! ;)

Íàä³ñëàíî ç iPhone

9 ëþò. 2015 î 16:34 martakostova <notifications@github.com> íàïèñàâ(ëà):

**Comment by martakostova** [comment]
Sorry for this. I would give your money back if I could. 
The oldest version was for 10.6 and above but the newest (2.1.0) is for 10.8 and above. It seems that the build you had downloaded has issue with this OS version.

All I can do for you is to make a build of the older version of the app and send it to you (if you want)

Cheers, 
Marta

**Comment by SashkoGarazd** [comment]
ok...yes, please - make a build of the older version for me.

Íàä³ñëàíî ç iPhone

13 ëþò. 2015 î 00:00 martakostova <notifications@github.com> íàïèñàâ(ëà):

**Comment by martakostova** [comment]
Here you are <a href="https://www.dropbox.com/s/jzoydycwn21h7lg/Timer2.0.3.zip?dl=0">Download v.2.0.3</a>

I hope it works as expected, please share feedback.

Cheers,
Marta
