### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by oschrenk** [martakostova/pomodoro#28]
```
make clean no-sig timer
Logging output to file 'make.log'
Cleaning up...
Removing signature information...
Building Timer.app...
** BUILD FAILED **


The following build commands failed:
        Ld /Users/oliver/Library/Developer/Xcode/DerivedData/Timer-eczfdxazowouiyacmenywqnnawln/Build/Products/Release/PomodoroTests.octest/Contents/MacOS/PomodoroTests normal x86_64
(1 failure)
make: *** [timer] Error 65
```

- [make.log](https://gist.github.com/oschrenk/40e4ece68ee29adb3329)

How can add some more output to the log for debugging?

**Comment by sanfm12** [comment]
Same here. My first time using Xcode (6.3.1). Is it because I don't have a developer program? I only want to build the app so that I can use applescripts...

**Comment by dltj** [comment]
FWIW, I'm seeing the same error.
