### ISSUE TITLE
Interrupt timer limit

### ISSUE THREAD

**Issue by rtechsolutions** [martakostova/pomodoro#29]
Back when Timer was Pomodoro, you could edit the plist file to change the number of seconds a timer interrupt could last beyond the maximum in the GUI (it doesn't except integers past 60). This does not appear to be supported anymore. I looked in the code to try and see where I would change that max value, but have yet to find the culprit. I would really appreciate being able to set it beyond 60 seconds (to a number of minutes) as I regularly get interrupted by phone calls. I'm happy to fix it myself if someone tells me where to look. Thanks!

**Comment by martakostova** [comment]
This is fixed in the latest version of the app.
Enjoy!
