### ISSUE TITLE
Calendar integration

### ISSUE THREAD

**Issue by esseti** [martakostova/pomodoro#32]
Is it working? if i try to refresh the list of the calendar they don't show up.
I'm basically not able to enable the feature.
(I built the app by myself)

**Comment by esseti** [comment]
After a bit it asks for permission and then you can use the calendar.

One problem `$dailyPomodoroDone` starts fro 0, why not from 1? i'm using it in the calendar.

**Comment by mainczjs** [comment]
The same problem here. Running it from xcode the cal worked, as xcode has access to my calendar. But building the app and running it independently from xcode yields no calendar access, as the app never asks for it. How can I solve this? Can I manually grant calendar access? (drag&drop in the preference/privacy panel didn't work)
Why does it not ask for permission to use the calendar?

Working on the most current version of OS X and xcode..

**Comment by esseti** [comment]
Check if you can turn it on via `Preferences` > `Security & Privacy` >  `Calendar`.

Still, pomodoro counter start from 0.

**Comment by mainczjs** [comment]
There is no such option under Preferences / Security & Privacy / Calendar
[Screenshot](http://d.pr/i/1fjmM)

**Comment by martakostova** [comment]
This is what asks for calendar permission https://github.com/martakostova/pomodoro/blob/master/Pomodoro/Pomodoro.entitlements#L15
@mainczjs check if this file is correct.

**Comment by agknaton** [comment]
Had the same problem, fixed this way:
- Enabled calendar integration and set a valid calendar name (Tasks, on my case)
- Started a pomodoro;
- Forced completion
At this moment a pop-up showed up asking for Calendar permission: that's it! Now refresh calendar list works, and Calendar Integration too.
