### ISSUE TITLE
Application breaks because on Zombie References on OSX 10.12

### ISSUE THREAD

**Issue by danielranziwerle** [martakostova/pomodoro#35]
After installing Sierra, app breaks when I try to start a Timer with sounds enabled.

Problem happens on PomodoroController.m line 120.

```
NSInteger volume = [[change objectForKey:NSKeyValueChangeNewKey] intValue];
NSInteger oldVolume = [[change objectForKey:NSKeyValueChangeOldKey] intValue];
		
if (volume != oldVolume) {
	float newVolume = volume/100.0;
	if ([keyPath isEqual:@"ringVolume"]) {
		[ringing setVolume:newVolume];
		[ringing play];
	}
	if ([keyPath isEqual:@"ringBreakVolume"]) {
		[ringingBreak setVolume:newVolume];
		[ringingBreak play];
	}
	if ([keyPath isEqual:@"tickVolume"]) {
		[tick setVolume:newVolume];
		[tick play];
	}
}
```

`ringing`, `ringingBreak`, and `tick` are all zombies when the `observeValueForKeyPath` is called after starting a timer.

**Comment by martakostova** [comment]
Thank you for reporting this. I will fix it with the next version.
Cheers!

**Comment by mainczjs** [comment]
Any chance this got resolved by now? I am able to start Timers, when I disable all sounds, though... So it doesn't break the app completely :-)

**Comment by martakostova** [comment]
@danielranziwerle  @jannismain there is a newer version of the app with this bug fixed. Enjoy!
Thank you for reporting it!
