### ISSUE TITLE
Timer disappears during breaks

### ISSUE THREAD

**Issue by katmoody** [martakostova/pomodoro#36]
The visual timer disappears during the breaks, making it hard to see how much break time is still available at a glance. :(

**Comment by martakostova** [comment]
Hi, @katmoody Thanks for this issue. What OS version do you use?

**Comment by katmoody** [comment]
Hey there - I'm on the newest version of iOS for Mac - but I think I figured this out. 

The visual timer only disappeared because the Chrome menu used more of that top header spot. If I reduced the size of my date/time display by cutting a couple elements, and took out the batter % warning amount I ended up with enough space to display the timer at all times even while using Chrome. Does that make sense? 

I don't know that it is something you can actually account for or whether you can just put in a little warning about it? Here's a screenshot with the top bar so you can see what I mean: 

<img width="1254" alt="screen shot 2016-11-28 at 9 42 01 am" src="https://cloud.githubusercontent.com/assets/5481211/20672345/fb9b6b66-b54e-11e6-9db9-4b46f287129a.png">

**Comment by martakostova** [comment]
Thank you! I'll play with it to check if I can do something. 
Cheers!
