### ISSUE TITLE
Applocation is not seeing the calendars on my computer

### ISSUE THREAD

**Issue by adriansalns** [martakostova/pomodoro#38]
Please help, I love the time app because it records my pomodoros back into my calendar, for some reason, it's the only app that does this and I use it all the time. but since a couple of days ago it stopped seeing the calendars, I tried reinstalling it, restarting the computer, and nothing works. if someone has a fix please let me know.

All the best, 
Adrian

**Comment by martakostova** [comment]
@adriansalns there is a newer version. Please check it out and tell me if it fixes your problem.
Thanks!
